"""Initial AgentGate MySQL schema"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agentgate_api_keys",
        sa.Column("id_key", sa.BINARY(length=32), nullable=False),
        sa.Column("id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("scope", mysql.VARCHAR(length=16), nullable=False),
        sa.Column("provider_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("metadata_payload", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("encrypted_api_key", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.PrimaryKeyConstraint("id_key", name=op.f("pk_agentgate_api_keys")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_bin",
        mysql_engine="InnoDB",
        mysql_row_format="DYNAMIC",
    )
    op.create_index("ix_api_keys_created", "agentgate_api_keys", ["created_at"], unique=False)
    op.create_table(
        "agentgate_dataset_versions",
        sa.Column("id_key", sa.BINARY(length=32), nullable=False),
        sa.Column("id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("dataset_key", sa.BINARY(length=32), nullable=False),
        sa.Column("dataset_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=True),
        sa.Column("status", mysql.VARCHAR(length=16), nullable=False),
        sa.Column("draft_slot", sa.SmallInteger(), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column(
            "content_sha256",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=64),
            nullable=False,
        ),
        sa.Column("user_team_key", sa.BINARY(length=32), nullable=False),
        sa.Column("user_team_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("user_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("user_name", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("payload", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.PrimaryKeyConstraint("id_key", name=op.f("pk_agentgate_dataset_versions")),
        sa.UniqueConstraint("dataset_key", "draft_slot", name="uq_dataset_draft"),
        sa.UniqueConstraint("dataset_key", "version", name="uq_dataset_publication"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_bin",
        mysql_engine="InnoDB",
        mysql_row_format="DYNAMIC",
    )
    op.create_index(
        "ix_dataset_versions_lookup",
        "agentgate_dataset_versions",
        ["dataset_key", "status", "version"],
        unique=False,
    )
    op.create_table(
        "agentgate_datasets",
        sa.Column("id_key", sa.BINARY(length=32), nullable=False),
        sa.Column("id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("name", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("archived", sa.SmallInteger(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("user_team_key", sa.BINARY(length=32), nullable=False),
        sa.Column("user_team_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("user_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("user_name", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("payload", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.PrimaryKeyConstraint("id_key", name=op.f("pk_agentgate_datasets")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_bin",
        mysql_engine="InnoDB",
        mysql_row_format="DYNAMIC",
    )
    op.create_index(
        "ix_datasets_team_updated",
        "agentgate_datasets",
        ["user_team_key", "updated_at"],
        unique=False,
    )
    op.create_table(
        "agentgate_evaluator_drafts",
        sa.Column("id_key", sa.BINARY(length=32), nullable=False),
        sa.Column("id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("evaluator_key", sa.BINARY(length=32), nullable=False),
        sa.Column("evaluator_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("user_team_key", sa.BINARY(length=32), nullable=False),
        sa.Column("user_team_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("user_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("user_name", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("payload", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.PrimaryKeyConstraint("id_key", name=op.f("pk_agentgate_evaluator_drafts")),
        sa.UniqueConstraint("evaluator_key", name="uq_evaluator_draft"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_bin",
        mysql_engine="InnoDB",
        mysql_row_format="DYNAMIC",
    )
    op.create_table(
        "agentgate_evaluator_versions",
        sa.Column("evaluator_key", sa.BINARY(length=32), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("evaluator_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column(
            "content_sha256",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=64),
            nullable=False,
        ),
        sa.Column("user_team_key", sa.BINARY(length=32), nullable=False),
        sa.Column("user_team_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("user_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("user_name", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("payload", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.PrimaryKeyConstraint(
            "evaluator_key", "version", name=op.f("pk_agentgate_evaluator_versions")
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_bin",
        mysql_engine="InnoDB",
        mysql_row_format="DYNAMIC",
    )
    op.create_table(
        "agentgate_evaluators",
        sa.Column("id_key", sa.BINARY(length=32), nullable=False),
        sa.Column("id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("source", mysql.VARCHAR(length=16), nullable=False),
        sa.Column("enabled", sa.SmallInteger(), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("user_team_key", sa.BINARY(length=32), nullable=False),
        sa.Column("user_team_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("user_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("user_name", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("payload", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.PrimaryKeyConstraint("id_key", name=op.f("pk_agentgate_evaluators")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_bin",
        mysql_engine="InnoDB",
        mysql_row_format="DYNAMIC",
    )
    op.create_index(
        "ix_evaluators_team_updated",
        "agentgate_evaluators",
        ["user_team_key", "enabled", "updated_at"],
        unique=False,
    )
    op.create_table(
        "agentgate_results",
        sa.Column("id_key", sa.BINARY(length=32), nullable=False),
        sa.Column("id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("run_key", sa.BINARY(length=32), nullable=False),
        sa.Column("run_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("case_key", sa.BINARY(length=32), nullable=False),
        sa.Column("case_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("trace_key", sa.BINARY(length=32), nullable=False),
        sa.Column("trace_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("evaluator_key", sa.BINARY(length=32), nullable=False),
        sa.Column("evaluator_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("payload", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.PrimaryKeyConstraint("id_key", name=op.f("pk_agentgate_results")),
        sa.UniqueConstraint(
            "run_key", "case_key", "evaluator_key", name="uq_result_run_case_evaluator"
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_bin",
        mysql_engine="InnoDB",
        mysql_row_format="DYNAMIC",
    )
    op.create_table(
        "agentgate_run_asset_refs",
        sa.Column("reference_key", sa.BINARY(length=32), nullable=False),
        sa.Column("run_key", sa.BINARY(length=32), nullable=False),
        sa.Column("run_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("asset_lookup_key", sa.BINARY(length=32), nullable=False),
        sa.Column("asset_kind", mysql.VARCHAR(length=16), nullable=False),
        sa.Column("source_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("asset_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("version", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column(
            "content_sha256",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=64),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("reference_key", name=op.f("pk_agentgate_run_asset_refs")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_bin",
        mysql_engine="InnoDB",
        mysql_row_format="DYNAMIC",
    )
    op.create_index(
        "ix_run_refs_lookup",
        "agentgate_run_asset_refs",
        ["asset_lookup_key", "content_sha256", "run_key"],
        unique=False,
    )
    op.create_index("ix_run_refs_run", "agentgate_run_asset_refs", ["run_key"], unique=False)
    op.create_table(
        "agentgate_runs",
        sa.Column("id_key", sa.BINARY(length=32), nullable=False),
        sa.Column("id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("status", mysql.VARCHAR(length=16), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("scheduled_for", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("user_team_key", sa.BINARY(length=32), nullable=False),
        sa.Column("user_team_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("user_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("user_name", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("api_key", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=True),
        sa.Column("payload", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.PrimaryKeyConstraint("id_key", name=op.f("pk_agentgate_runs")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_bin",
        mysql_engine="InnoDB",
        mysql_row_format="DYNAMIC",
    )
    op.create_index(
        "ix_runs_due", "agentgate_runs", ["status", "scheduled_for", "created_at"], unique=False
    )
    op.create_index(
        "ix_runs_status_created", "agentgate_runs", ["status", "created_at"], unique=False
    )
    op.create_index(
        "ix_runs_team_created", "agentgate_runs", ["user_team_key", "created_at"], unique=False
    )
    op.create_index(
        "ix_runs_team_status",
        "agentgate_runs",
        ["user_team_key", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "agentgate_skill_analysis_reports",
        sa.Column("id_key", sa.BINARY(length=32), nullable=False),
        sa.Column("id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column(
            "target_descriptor_sha256",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=64),
            nullable=False,
        ),
        sa.Column(
            "content_sha256",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=64),
            nullable=False,
        ),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("payload", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.PrimaryKeyConstraint("id_key", name=op.f("pk_agentgate_skill_analysis_reports")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_bin",
        mysql_engine="InnoDB",
        mysql_row_format="DYNAMIC",
    )
    op.create_index(
        "ix_skill_reports_target",
        "agentgate_skill_analysis_reports",
        ["target_descriptor_sha256", "created_at"],
        unique=False,
    )
    op.create_table(
        "agentgate_skill_analysis_reviews",
        sa.Column("report_key", sa.BINARY(length=32), nullable=False),
        sa.Column("finding_key", sa.BINARY(length=32), nullable=False),
        sa.Column("report_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("finding_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("reviewed_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("payload", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.PrimaryKeyConstraint(
            "report_key", "finding_key", name=op.f("pk_agentgate_skill_analysis_reviews")
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_bin",
        mysql_engine="InnoDB",
        mysql_row_format="DYNAMIC",
    )
    op.create_table(
        "agentgate_target_descriptors",
        sa.Column(
            "content_sha256",
            mysql.CHAR(charset="ascii", collation="ascii_bin", length=64),
            nullable=False,
        ),
        sa.Column("target_ref_key", sa.BINARY(length=32), nullable=False),
        sa.Column("source_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("target_type", mysql.VARCHAR(length=16), nullable=False),
        sa.Column("external_target_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("external_version_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("fetched_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("payload", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.PrimaryKeyConstraint("content_sha256", name=op.f("pk_agentgate_target_descriptors")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_bin",
        mysql_engine="InnoDB",
        mysql_row_format="DYNAMIC",
    )
    op.create_index(
        "ix_target_ref",
        "agentgate_target_descriptors",
        ["target_ref_key", "fetched_at"],
        unique=False,
    )
    op.create_table(
        "agentgate_traces",
        sa.Column("id_key", sa.BINARY(length=32), nullable=False),
        sa.Column("id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("run_key", sa.BINARY(length=32), nullable=False),
        sa.Column("run_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("case_key", sa.BINARY(length=32), nullable=False),
        sa.Column("case_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("payload", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.PrimaryKeyConstraint("id_key", name=op.f("pk_agentgate_traces")),
        sa.UniqueConstraint("run_key", "case_key", name="uq_trace_run_case"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_bin",
        mysql_engine="InnoDB",
        mysql_row_format="DYNAMIC",
    )
    op.create_table(
        "evaluation_task_runs",
        sa.Column("run_key", sa.BINARY(length=32), nullable=False),
        sa.Column("run_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("task_key", sa.BINARY(length=32), nullable=False),
        sa.Column("task_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.PrimaryKeyConstraint("run_key", name=op.f("pk_evaluation_task_runs")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_bin",
        mysql_engine="InnoDB",
        mysql_row_format="DYNAMIC",
    )
    op.create_index("ix_task_runs_task", "evaluation_task_runs", ["task_key"], unique=False)
    op.create_table(
        "evaluation_tasks",
        sa.Column("id_key", sa.BINARY(length=32), nullable=False),
        sa.Column("id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("payload", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.PrimaryKeyConstraint("id_key", name=op.f("pk_evaluation_tasks")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_bin",
        mysql_engine="InnoDB",
        mysql_row_format="DYNAMIC",
    )
    op.create_index("ix_tasks_created", "evaluation_tasks", ["created_at"], unique=False)
    op.create_table(
        "optimization_reports",
        sa.Column("evidence_key_digest", sa.BINARY(length=32), nullable=False),
        sa.Column("evidence_key", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("run_key", sa.BINARY(length=32), nullable=False),
        sa.Column("run_id", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("payload", mysql.LONGTEXT(collation="utf8mb4_bin"), nullable=False),
        sa.PrimaryKeyConstraint("evidence_key_digest", name=op.f("pk_optimization_reports")),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_bin",
        mysql_engine="InnoDB",
        mysql_row_format="DYNAMIC",
    )
    op.create_index("ix_optimization_run", "optimization_reports", ["run_key"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_optimization_run", table_name="optimization_reports")
    op.drop_table("optimization_reports")
    op.drop_index("ix_tasks_created", table_name="evaluation_tasks")
    op.drop_table("evaluation_tasks")
    op.drop_index("ix_task_runs_task", table_name="evaluation_task_runs")
    op.drop_table("evaluation_task_runs")
    op.drop_table("agentgate_traces")
    op.drop_index("ix_target_ref", table_name="agentgate_target_descriptors")
    op.drop_table("agentgate_target_descriptors")
    op.drop_table("agentgate_skill_analysis_reviews")
    op.drop_index("ix_skill_reports_target", table_name="agentgate_skill_analysis_reports")
    op.drop_table("agentgate_skill_analysis_reports")
    op.drop_index("ix_runs_team_status", table_name="agentgate_runs")
    op.drop_index("ix_runs_team_created", table_name="agentgate_runs")
    op.drop_index("ix_runs_status_created", table_name="agentgate_runs")
    op.drop_index("ix_runs_due", table_name="agentgate_runs")
    op.drop_table("agentgate_runs")
    op.drop_index("ix_run_refs_run", table_name="agentgate_run_asset_refs")
    op.drop_index("ix_run_refs_lookup", table_name="agentgate_run_asset_refs")
    op.drop_table("agentgate_run_asset_refs")
    op.drop_table("agentgate_results")
    op.drop_index("ix_evaluators_team_updated", table_name="agentgate_evaluators")
    op.drop_table("agentgate_evaluators")
    op.drop_table("agentgate_evaluator_versions")
    op.drop_table("agentgate_evaluator_drafts")
    op.drop_index("ix_datasets_team_updated", table_name="agentgate_datasets")
    op.drop_table("agentgate_datasets")
    op.drop_index("ix_dataset_versions_lookup", table_name="agentgate_dataset_versions")
    op.drop_table("agentgate_dataset_versions")
    op.drop_index("ix_api_keys_created", table_name="agentgate_api_keys")
    op.drop_table("agentgate_api_keys")
    # ### end Alembic commands ###
