import {test,expect} from '@playwright/test'

test('restored history and unified creation use real API responses',async({page,request})=>{
 const runs=await (await request.get('/api/runs?limit=200')).json()
 expect(runs.length).toBeGreaterThanOrEqual(46)
 const errors:string[]=[]
 page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/#tasks')
 await expect(page.getByRole('button',{name:'单任务',exact:true})).toBeVisible()
 await expect(page.getByRole('button',{name:'A/B 实验',exact:true})).toBeVisible()
 await expect(page.getByRole('combobox',{name:'执行状态筛选'})).toBeVisible()
 await expect(page.locator('.sidebar').getByRole('link',{name:'A/B 实验'})).toHaveCount(0)
 await page.getByRole('button',{name:'发起评测',exact:true}).click()
 const dialog=page.getByRole('dialog')
 await expect(dialog.getByText('查看智能体定义',{exact:true})).toHaveCount(0)
 await expect(dialog.getByRole('combobox',{name:'关联 Git 分支'})).toBeEnabled()
 await expect(dialog.getByRole('combobox',{name:'任务评测集'}).locator('option')).not.toHaveCount(0)
 await dialog.getByRole('button',{name:'采用推荐并查看理由'}).click()
 await expect(dialog.getByText('推荐理由：').first()).toBeVisible()
 await dialog.locator('.evaluator-guide').screenshot({path:'../runtime/evaluator-redesign.png'})
 await dialog.getByRole('button',{name:/^工具调用/}).click()
 await dialog.locator('.evaluator-row button').filter({hasText:'禁用工具'}).click()
 await expect(dialog.getByRole('complementary',{name:'评估器推荐依据'}).getByRole('heading',{name:'推荐理由：',exact:true})).toBeVisible()
 await dialog.getByRole('button',{name:'已加入 · 点击移除',exact:true}).click()
 await expect(dialog.getByRole('checkbox',{name:'选择禁用工具',exact:true})).not.toBeChecked()
 await dialog.getByRole('button',{name:'＋ 加入本次评测',exact:true}).click()
 await expect(dialog.getByRole('checkbox',{name:'选择禁用工具',exact:true})).toBeChecked()
 await dialog.getByRole('button',{name:'确认评估器'}).click()
 await expect(dialog.getByRole('button',{name:'已确认评估器'})).toBeDisabled()
 await dialog.getByRole('button',{name:/A\/B 实验/}).click()
 await expect(dialog.getByRole('combobox',{name:'实验 B · 候选版本'})).toBeVisible()
 const boxes=await Promise.all(['智能体','关联 Git 分支','智能体版本','实验 B · 候选版本'].map(name=>dialog.getByRole('combobox',{name,exact:true}).boundingBox()))
 expect(Math.abs(boxes[0]!.y-boxes[1]!.y)).toBeLessThan(2)
 expect(Math.abs(boxes[2]!.y-boxes[3]!.y)).toBeLessThan(2)
 expect(Math.abs(boxes[0]!.width-boxes[3]!.width)).toBeLessThan(2)
 await dialog.locator('.target-choice').screenshot({path:'../runtime/target-redesign.png'})
 await expect(dialog.getByRole('combobox',{name:'静态分析模型来源'})).toHaveCount(0)
 await expect(dialog.getByRole('checkbox',{name:/Skill 静态分析/})).toBeVisible()
 await page.screenshot({path:'../runtime/unified-form.png',fullPage:true})
 await dialog.getByRole('button',{name:'取消',exact:true}).click()
 expect(errors).toEqual([])
})

test('create A/B via the shared form, then retrieve real comparison',async({page,request})=>{
 await page.goto('/#tasks')
 await page.getByRole('button',{name:'发起评测',exact:true}).click()
 const dialog=page.getByRole('dialog')
 await dialog.getByRole('button',{name:/A\/B 实验/}).click()
 await dialog.getByRole('button',{name:'采用推荐并查看理由'}).click()
 const response=page.waitForResponse(r=>r.url().endsWith('/api/run-comparisons')&&r.request().method()==='POST')
 await dialog.getByRole('button',{name:'创建 A/B 实验',exact:true}).click()
 await page.getByRole('button',{name:'按实际配置执行',exact:true}).click()
 const result=await response
 expect(result.status()).toBe(202)
 const pair=await result.json()
 await expect(dialog).not.toBeVisible()
 await expect.poll(async()=>{
  const states=await Promise.all([pair.baseline.run_id,pair.candidate.run_id].map(async id=>(await (await request.get('/api/runs/'+id+'/status')).json()).status))
  return states
 },{timeout:45000}).toEqual(['completed','completed'])
 await expect(page.getByRole('heading',{name:'结果对比',exact:true})).toBeVisible({timeout:15000})
 await page.goto('/#tasks')
 await page.getByRole('button',{name:'A/B 实验',exact:true}).click()
 await expect(page.locator('tbody tr')).toHaveCount(1)
 await page.reload()
 await page.getByRole('button',{name:'A/B 实验',exact:true}).click()
 await expect(page.locator('tbody tr')).toHaveCount(1)
})

test('single task calls real static analysis and opens its report',async({page,request})=>{
 test.setTimeout(300000)
 await page.goto('/#tasks')
 await page.getByRole('button',{name:'发起评测',exact:true}).click()
 const dialog=page.getByRole('dialog')
 await dialog.getByRole('button',{name:'采用推荐并查看理由'}).click()
 await dialog.getByRole('checkbox',{name:/同时运行 Skill 静态分析/}).check()
 const reportResponse=page.waitForResponse(r=>r.url().endsWith('/api/evaluations/skill-analysis')&&r.request().method()==='POST',{timeout:250000})
 await dialog.getByRole('button',{name:'开始评测',exact:true}).click()
 await page.getByRole('button',{name:'按实际配置执行',exact:true}).click()
 const response=await reportResponse
 expect(response.status()).toBe(201)
 const report=await response.json()
 expect(['completed','partial']).toContain(report.status)
 const saved=await (await request.get('/api/skill-analysis/reports/'+report.id)).json()
 expect(saved.report.id).toBe(report.id)
 await expect(dialog).not.toBeVisible()
 await page.getByRole('button',{name:'Skill 静态分析',exact:true}).click()
 await expect(page.getByRole('heading',{name:'第三步：查看问题与修改建议',exact:true})).toBeVisible()
})

test('bulk actions and explicit mock selectors',async({page})=>{
 await page.goto('/#tasks')
 await expect(page.getByRole('combobox',{name:'评估结论筛选'})).toHaveCount(0)
 await page.getByRole('button',{name:'发起评测',exact:true}).click()
 const dialog=page.getByRole('dialog')
 await expect(dialog.locator('.form-section-heading h3')).toHaveText(['任务类型','评测对象','评测数据','评估方式','执行设置'])
 await expect(dialog.locator('.form-section-heading>span')).toHaveText(['01','02','03','04','05'])
 await expect(dialog.locator('.task-intro')).toHaveCount(0)
 await dialog.getByRole('combobox',{name:'关联 Git 分支'}).selectOption('feature/prompt-tuning')
 await dialog.getByRole('button',{name:'全选',exact:true}).click()
 await dialog.getByRole('button',{name:/^全部\s+8$/}).click()
 await expect(dialog.getByRole('checkbox',{checked:true})).toHaveCount(8)
 await dialog.getByRole('button',{name:'全部取消',exact:true}).click()
 await expect(dialog.getByRole('checkbox',{checked:true})).toHaveCount(0)
 await dialog.getByRole('button',{name:'采用推荐并查看理由'}).click()
 await expect(dialog.getByRole('region',{name:'智能体内部推荐依据'})).toContainText('loan_approval')
 await expect(dialog.getByRole('region',{name:'智能体内部推荐依据'})).toContainText('approve_loan')
 await expect(dialog.getByRole('region',{name:'智能体内部推荐依据'})).toContainText('接口未提供提示词正文')
 await expect(dialog.getByRole('region',{name:'Skill 静态分析模型配置'})).toHaveCount(0)
 await dialog.getByRole('checkbox',{name:/Skill 静态分析/}).check()
 await expect(dialog.getByRole('combobox',{name:'静态分析模型来源'})).toHaveValue('platform')
 await expect(dialog.getByRole('textbox',{name:'Base URL',exact:true})).toHaveCount(0)
 await dialog.getByRole('combobox',{name:'静态分析模型来源'}).selectOption('custom')
 await expect(dialog.getByRole('textbox',{name:'Base URL',exact:true})).toHaveValue('https://model.example.com/compatible-mode/v1')
 await expect(dialog.getByRole('textbox',{name:'API Key',exact:true})).toHaveValue('DEMO-ONLY-NOT-A-REAL-API-KEY')
 await expect(dialog.getByRole('combobox',{name:'模型名称',exact:true})).toHaveValue('deepseek-v3.2')
 await expect(dialog.locator('.mock-notice')).toContainText('Mock 示例配置')
 await dialog.getByRole('textbox',{name:'Base URL',exact:true}).fill('https://example.com/v1')
 await dialog.getByRole('textbox',{name:'API Key',exact:true}).fill('test-not-a-real-secret')
 await expect(dialog.getByRole('textbox',{name:'API Key',exact:true})).toHaveAttribute('type','password')
 await dialog.getByRole('combobox',{name:'模型名称',exact:true}).selectOption('qwen-plus')
 await expect(dialog.locator('.mock-notice')).toContainText('不会发送或保存')
 const posts:string[]=[]
 page.on('request',r=>{if(r.method()==='POST'&&r.url().includes('/api/'))posts.push(r.url())})
 await dialog.getByRole('button',{name:'开始评测',exact:true}).click()
 await expect(page.getByText('Git 分支与模型配置仅用于前端展示，尚未接入执行。继续后将使用已选智能体版本及服务端实际模型配置运行；此处填写的 API Key 不会发送或保存。')).toBeVisible()
 await page.getByRole('button',{name:'返回修改',exact:true}).click()
 await dialog.getByRole('checkbox',{name:/Skill 静态分析/}).uncheck()
 await expect(dialog.getByRole('region',{name:'Skill 静态分析模型配置'})).toHaveCount(0)
 await dialog.getByRole('checkbox',{name:/Skill 静态分析/}).check()
 await expect(dialog.getByRole('combobox',{name:'静态分析模型来源'})).toHaveValue('platform')
 expect(posts).toEqual([])
})

test('task tuning is inline with three functional columns and static analysis',async({page,request})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(String(e)))
 const runs=await (await request.get('/api/runs?limit=200')).json()
 const a=runs.find((r:any)=>r.status==='completed'&&r.manifest.target.ref.external_version_id==='loan-agent-v1-risky')
 const b=runs.find((r:any)=>r.status==='completed'&&r.manifest.target.ref.external_version_id==='loan-agent-v2-fixed')
 await page.addInitScript(pair=>localStorage.setItem('agentgate:task-links:v1',JSON.stringify([{id:pair[0],kind:'ab',runIds:pair,staticReports:[]}])) ,[a.id,b.id])
 await page.goto('/#tasks')
 await page.getByRole('button',{name:'A/B 实验',exact:true}).click()
 await expect(page.locator('.ab-identities')).toContainText('loan-agent-v1-risky')
 await expect(page.locator('.ab-identities')).toContainText('loan-agent-v2-fixed')
 await expect(page.locator('.sidebar').getByText('Skill 静态分析')).toHaveCount(0)
 await expect(page.getByRole('button',{name:'调优分析',exact:true})).toHaveCount(0)
 await page.getByRole('button',{name:'查看详情',exact:true}).click()
 await expect(page.locator('[aria-label="实验详情内容"] button')).toHaveText(['实验对比','调优分析','Skill 静态分析'])
 await page.getByRole('button',{name:'调优分析',exact:true}).click()
 await expect(page.getByRole('heading',{name:'分析结果',exact:true})).toBeVisible()
 const boxes=await Promise.all(['.tuning-evaluators','.tuning-cases','.tuning-notes'].map(s=>page.locator(s).boundingBox()))
 expect(Math.abs(boxes[0]!.y-boxes[2]!.y)).toBeLessThan(2)
 expect(boxes[1]!.x).toBeGreaterThan(boxes[0]!.x)
 expect(boxes[2]!.x).toBeGreaterThan(boxes[1]!.x)
 await page.locator('.tuning-workbench').screenshot({path:'../runtime/tuning-functional-columns.png'})
 const picker=page.getByRole('combobox',{name:'选择分析用例'})
 const ids=await picker.locator('option').evaluateAll(opts=>opts.map(o=>(o as HTMLOptionElement).value))
 await page.locator('.tuning-notes textarea').fill('界面测试备注，不写入后端')
 if(ids.length>1){
 await picker.selectOption(ids[1]);await expect(page.locator('.tuning-notes textarea')).toHaveValue('')
 await picker.selectOption(ids[0]);await expect(page.locator('.tuning-notes textarea')).toHaveValue('界面测试备注，不写入后端')
 }
 await page.getByRole('button',{name:'查看完整样本评测报告 ↗'}).click()
 await expect(page.getByRole('dialog',{name:'样本评测报告'})).toBeVisible()
 await page.getByRole('dialog',{name:'样本评测报告'}).getByRole('button',{name:'Close this dialog'}).click()
 const posts:string[]=[];page.on('request',r=>{if(r.method()==='POST')posts.push(r.url())})
 await page.getByRole('button',{name:'Skill 静态分析',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Skill 静态分析',exact:true})).toBeVisible()
 await expect(page.getByLabel('本次任务评测对象')).toContainText('loan-agent-v1-risky')
 await expect(page.getByRole('heading',{name:'本次任务评测对象',exact:true})).toBeVisible()
 await expect(page.getByRole('combobox',{name:'分析对象',exact:true})).toHaveCount(0)
 await page.getByRole('button',{name:'实验 B · 候选',exact:true}).click()
 await expect(page.getByLabel('本次任务评测对象')).toContainText('loan-agent-v2-fixed')
 const single=runs.find((r:any)=>r.status==='completed'&&r.id!==a.id&&r.id!==b.id)
 await page.goto('/#tasks/'+single.id)
 await expect(page.locator('.task-linked-summary')).toHaveCount(0)
 await expect(page.getByRole('button',{name:'查看调优分析',exact:true})).toHaveCount(0)
 await expect(page.locator('[aria-label="任务详情内容"] button')).toHaveText(['评测结果','调优分析','Skill 静态分析'])
 await page.getByRole('button',{name:'Skill 静态分析',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Skill 静态分析',exact:true})).toBeVisible()
 expect(posts).toEqual([]);expect(errors).toEqual([])
})

test('task overview stays above detail tabs',async({page})=>{
 await page.goto('/#tasks/8d740b98-f87a-4b4f-99b2-611eedc58a75')
 const overview=page.getByRole('region',{name:'任务结果总览'})
 await expect(overview).toBeVisible()
 await expect(overview).toContainText('31.3')
 await expect(page.getByText('本次任务配置与版本来源',{exact:true})).toHaveCount(1)
 const summary=await overview.boundingBox(),tabs=await page.locator('[aria-label="任务详情内容"]').boundingBox()
 expect(summary!.y+summary!.height).toBeLessThanOrEqual(tabs!.y)
 await page.screenshot({path:'../runtime/task-overview.png',fullPage:true})
 await page.getByRole('button',{name:'调优分析',exact:true}).click()
 await expect(overview).toBeVisible()
})

test('execution numeric fields expose ranges and validate edits',async({page})=>{
 await page.goto('/#tasks')
 await page.getByRole('button',{name:'发起评测',exact:true}).click()
 const dialog=page.getByRole('dialog')
 await dialog.getByRole('button',{name:'采用推荐并查看理由'}).click()
 const fields=[['稳定性测试','1','20'],['并发样本数','1','32'],['执行超时（秒）','1','3600'],['失败重试次数','0','5']]
 const posts:string[]=[]
 page.on('request',r=>{if(r.method()==='POST')posts.push(r.url())})
 for(const [name,min,max] of fields){
 const field=dialog.getByRole('spinbutton',{name,exact:true})
 await expect(field).toBeEnabled();await expect(field).toHaveAttribute('min',min);await expect(field).toHaveAttribute('max',max)
 await field.fill(String(Number(max)+1))
 await dialog.getByRole('button',{name:'开始评测',exact:true}).click()
 await expect(dialog.getByRole('alert')).toContainText('必须为')
 await field.fill(min)
 }
 const repeat=dialog.getByRole('spinbutton',{name:'稳定性测试',exact:true})
 await repeat.fill('3')
 await dialog.getByRole('button',{name:'开始评测',exact:true}).click()
 await expect(dialog.getByRole('alert')).toContainText('稳定性多次执行尚未接入后端')
 await repeat.fill('1.5')
 await dialog.getByRole('button',{name:'开始评测',exact:true}).click()
 await expect(dialog.getByRole('alert')).toContainText('整数')
 expect(posts).toEqual([])
})

test('compact execution settings and evaluator confirmation layout',async({page})=>{
 await page.goto('/#tasks')
 await page.getByRole('button',{name:'发起评测',exact:true}).click()
 const dialog=page.getByRole('dialog')
 await expect(dialog.getByText('了解这个检查项',{exact:true})).toHaveCount(0)
 await expect(dialog.locator('.selection-footer')).toHaveCount(0)
 await expect(dialog.locator('.evaluator-options').getByRole('button',{name:'确认评估器',exact:true})).toBeVisible()
 const fields=dialog.locator('.execution-settings>.field')
 await expect(fields).toHaveCount(5)
 const boxes=await Promise.all([0,1,2,3,4].map(i=>fields.nth(i).boundingBox()))
 expect(Math.abs(boxes[0]!.y-boxes[4]!.y)).toBeLessThan(2)
 await dialog.locator('.execution-settings').screenshot({path:'../runtime/compact-execution.png'})
 await page.setViewportSize({width:600,height:900})
 await expect(dialog.locator('.execution-settings')).toBeVisible()
 const mobile=await dialog.locator('.execution-settings').boundingBox()
 expect(mobile!.width).toBeLessThan(600)
})

test('LLM and composite drafts have editors while rules do not',async({page,request})=>{
 const list=await (await request.get('/api/evaluators?include_disabled=true')).json()
 expect(list.filter((e:any)=>e.kind==='rule'&&e.has_draft)).toEqual([])
 const writes:string[]=[];page.on('request',r=>{if(['POST','PUT','PATCH','DELETE'].includes(r.method()))writes.push(r.url())})
 await page.goto('/#evaluators')
 await page.getByRole('button',{name:'自建评估器',exact:true}).click()
 await page.getByRole('button',{name:'LLM 评估器',exact:true}).click()
 await page.getByRole('button',{name:'新建 LLM 评估器',exact:true}).click()
 const dialog=page.getByRole('dialog',{name:'新建评估器草稿'})
 await expect(dialog.getByRole('textbox',{name:'评分说明',exact:true})).toBeVisible()
 await expect(dialog.getByRole('combobox',{name:'评估器类型'}).locator('option[value="rule"]')).toHaveCount(0)
 await dialog.getByRole('button',{name:'取消',exact:true}).click()
 await page.getByRole('button',{name:'复合评估器',exact:true}).click()
 await page.getByRole('button',{name:'新建复合评估器',exact:true}).click()
 await expect(dialog.getByRole('combobox',{name:'组合方式',exact:true})).toBeVisible()
 await expect(dialog.getByRole('button',{name:'保存草稿',exact:true})).toBeEnabled()
 expect(writes).toEqual([])
})

test('evaluator catalog filters and readonly rule detail modal',async({page})=>{
 const writes:string[]=[];page.on('request',r=>{if(['POST','PUT','PATCH','DELETE'].includes(r.method()))writes.push(r.url())})
 await page.goto('/#evaluators')
 const cards=page.locator('.evaluator-catalog-card')
 await expect(cards.first()).toBeVisible()
 const boxes=await cards.evaluateAll(es=>es.slice(0,2).map(e=>({x:e.getBoundingClientRect().x,y:e.getBoundingClientRect().y})))
 expect(boxes[0].y).toBe(boxes[1].y);expect(boxes[1].x).toBeGreaterThan(boxes[0].x)
 await page.getByRole('button',{name:'规则评估器',exact:true}).click()
 await expect(page.getByRole('button',{name:'新建 LLM 评估器',exact:true})).toHaveCount(0)
 await page.screenshot({path:'../runtime/evaluator-catalog.png',fullPage:true})
 await cards.first().click()
 const detail=page.getByRole('dialog',{name:'评估器详情',exact:true})
 await expect(detail.getByRole('heading',{name:'前置条件',exact:true})).toBeVisible()
 await expect(detail.getByRole('heading',{name:'结果呈现位置',exact:true})).toBeVisible()
 await detail.evaluate(el=>Promise.all(el.getAnimations({subtree:true}).map(a=>a.finished.catch(()=>{}))))
 await page.screenshot({path:'../runtime/evaluator-detail.png'})
 await expect(detail.getByRole('button',{name:/^(概览|评估器设计|判定依据|实现源码)$/})).toHaveCount(0)
 await expect(detail.getByRole('region',{name:'评估器属性'})).toHaveCount(0)
 await expect(detail.locator('.evaluator-display-tags')).toHaveText('预置代码仅看结果')
 await expect(detail.getByRole('button',{name:/创建草稿|复制为草稿/})).toHaveCount(0)
 await detail.getByRole('button',{name:'关闭',exact:true}).click()
 await page.getByRole('textbox',{name:'搜索评估器',exact:true}).fill('不存在的评估器xyz')
 await expect(page.getByText('暂无匹配的评估器', {exact:true})).toBeVisible()
 await page.getByRole('button',{name:'清空',exact:true}).click()
 await expect(cards.first()).toBeVisible()
 expect(writes).toEqual([])
})

test('launch from imported rule preselects it and hides version diff',async({page,request})=>{
 const list=await(await request.get('/api/evaluators?include_disabled=true')).json()
 const e=list.find((x:any)=>x.kind==='rule'&&x.enabled&&/^联调导入规则/.test(x.name))
 expect(e).toBeTruthy()
 await page.goto('/#evaluators/'+e.id)
 await page.getByRole('dialog',{name:'评估器详情',exact:true}).getByRole('button',{name:'发起评测',exact:true}).click()
 const form=page.getByRole('dialog',{name:'新建评测任务',exact:true})
 await expect(form.getByRole('checkbox',{name:'选择'+e.name,exact:true})).toBeChecked()
 await expect(form.locator('.task-summary')).toContainText('1 个评估器')
 await page.goto('/#evaluators/answer-quality')
 await expect(page.getByRole('dialog',{name:'评估器详情',exact:true})).toBeVisible()
 await expect(page.getByText('版本差异',{exact:true})).toHaveCount(0)
})

test('rule import publishes via API and does not leave an editable draft',async({page})=>{
 // Isolated API responses exercise the UI workflow without creating catalog records.
 const calls:string[]=[]
 await page.route('**/api/evaluators',async route=>{
  if(route.request().method()!=='POST')return route.continue()
  calls.push('create');await route.fulfill({json:{evaluator:{id:'import-workflow-test'}}})
 })
 await page.route('**/api/evaluators/import-workflow-test/drafts/publish',async route=>{
  calls.push('publish');await route.fulfill({json:{}})
 })
 await page.goto('/#evaluators')
 await page.getByRole('button',{name:'导入评估器',exact:true}).click()
 const dialog=page.getByRole('dialog',{name:'导入评估器配置'})
 await dialog.getByLabel('评估器配置文件').setInputFiles({name:'rule.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({name:'测试导入',kind:'rule',dimension:'routing',metric:'skill_routing_accuracy',severity:'standard',implementation_id:'skill_routing',implementation_version:'1',config:{}}))})
 await dialog.getByRole('button',{name:'导入并发布',exact:true}).click()
 await expect(dialog).not.toBeVisible()
 expect(calls).toEqual(['create','publish'])
})
